//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MPEntities : DbContext
    {
        public MPEntities()
            : base("name=MPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminInfo> AdminInfoes { get; set; }
        public virtual DbSet<NavMenu> NavMenus { get; set; }
        public virtual DbSet<SceneryInfo> SceneryInfoes { get; set; }
        public virtual DbSet<TrainInfo> TrainInfoes { get; set; }
        public virtual DbSet<MovieInfo> MovieInfoes { get; set; }
    }
}
