//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEn { get; set; }
        public string Image { get; set; }
        public Nullable<double> Rating { get; set; }
        public string Cast { get; set; }
        public string Direction { get; set; }
        public string Genre { get; set; }
        public string Duration { get; set; }
        public string ReLink { get; set; }
        public int IsDele { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    }
}
