//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SceneryInfo
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Value { get; set; }
        public string TopBanner { get; set; }
        public string UEValue { get; set; }
        public int IsDele { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    }
}
